services:
  lms_app:
    image: lms2025:latest
    build:
      context: ..
      dockerfile: Dockerfile
    ports:
      - "9099:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/lmsdb
      - SPRING_DATASOURCE_USERNAME=lms
      - SPRING_DATASOURCE_PASSWORD=postgres
    depends_on:
      - postgres  # Đảm bảo postgres được khởi động trước
    restart: always

  chatbot-server:
    image: chatbot_server:latest
    build: ../chatbot-server
    container_name: chatbot_server
    ports:
      - "7500:7500"
    restart: unless-stopped

  postgres:
    image: postgres:16   # Chọn phiên bản PostgreSQL 16
    environment:
      - POSTGRES_DB=lmsdb
      - POSTGRES_USER=lms
      - POSTGRES_PASSWORD=postgres
    ports:
      - "15437:5432"
    volumes:
      - ./data/postgresql:/var/lib/postgresql/data   # Mount thư mục data vào container PostgresSQL
    restart: always

  nginx:
    #    build:
    #      context: ../nginx
    image: nginx:latest
    # ports:
    #   - "80:80"
    volumes:
      - ../src/main/resources/static/templates/material:/usr/share/nginx/html/material
      - ../nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - lms_app
      - chatbot-server
    restart: always

  cloudflared:
    image: cloudflare/cloudflared:latest
    command: tunnel run
    restart: always
    environment:
      # - TUNNEL_TRANSPORT_PROTOCOL=quic
      - TUNNEL_ORIGIN_KEEPALIVE_TIMEOUT=30s
      - "TUNNEL_TOKEN=${CLOUDFLARE_TUNNEL_TOKEN}"
      - NO_AUTOUPDATE
    healthcheck:
      test: [ "CMD", "cloudflared", "--version" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    ulimits:
      nproc: 65535
      nofile:
        soft: 65535
        hard: 65535
    sysctls:
      - net.core.somaxconn=65535
      - net.ipv4.tcp_max_syn_backlog=65535
      - net.ipv4.ip_local_port_range=1024 65535
      - net.ipv4.tcp_tw_reuse=1
